### ISSUE TITLE
Error on parsing yakuza 0 kiryu model

### ISSUE THREAD

**Issue by FlashlightET** [Poyo-SSB/GMDTool#1]
the issue could just be because its not a persona game
```
C:\Users\EzoGaming\Downloads\GMDTool-v1.1.3>GMDTool.exe "F:\SteamLibrary\steamapps\common\Yakuza 0\media\data\chara\w64\adv\c_cm_kiryu\c_cm_kiryu_ps4.gmd" -b

Unhandled Exception: System.IO.InvalidDataException: Unknown/Invalid resource type
   at GFDLibrary.Resource.Load(Stream stream, Boolean leaveOpen)
   at GFDLibrary.Resource.Load(String path)
   at GFDLibrary.Resource.Load[T](String path)
   at GMDTool.Convert.GMDConverter..ctor(GMDConverterOptions options)
   at GMDTool.Program.<>c.<Main>b__2_1(GMDConverterOptions o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at GMDTool.Program.Main(String[] args)```

**Comment by lemoncove** [comment]
I'm not sure if Yakuza 0 uses the same engine as the Persona/Catherine games. If you could post an example GMD file I can take a look and verify if that's the case, in which case you should take this issue to [GFD-Studio](https://github.com/TGEnigma/GFD-Studio), which is the library that actually handles the conversion of the model.
